test: test

diff --git a/.github/workflows/sync-issues.yml b/.github/workflows/sync-issues.yml
--- a/.github/workflows/sync-issues.yml
+++ b/.github/workflows/sync-issues.yml
@@ -45,4 +45,10 @@ jobs:
           TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
           TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
           TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
-        run: echo $ARTIFACT_CONTENTS
+        run: |
+          set -e
+          ARTIFACT_CONTENTS=$(actions/download-artifact@v2 --name twitterMap || echo "Artifact not found.")
+          if [ "$ARTIFACT_CONTENTS" == "Artifact not found." ]; then
+            exit 0
+          fi
+          npx tsx index.ts "$ARTIFACT_CONTENTS"
